name: Java CI with Maven

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

env:
  RootPassword: mypassword

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Set up MySQL
        run: docker pull mysql
      - name: Run MySQL image
        run: docker run --name my-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=$RootPassword -d mysql

#      - name: Setup Kafka
#        # You may pin to the exact commit or the version.
#        # uses: 280780363/kafka-action@a66f129ffd34e42d6245b7e25d69e94659a1d444
#        uses: 280780363/kafka-action@v1.0
#        with:
#          # Version of Bitnami Kafka to use
#          kafka version: latest
#          # Version of Bitnami Zookeeper to use
#          zookeeper version: latest
#          # The port of Kafka host
#          kafka port: 9092
#          # The port of Zookeeper host
#          zookeeper port: 2181
#          # Configure of auto.create.topics.enable
#          auto create topic: true
#          create topic: customer-topic

      #     - name: Build with Maven
      #       run: mvn clean install
      #       run: mvn -B package --file customer-service/pom.xml

      - name: Build the Docker image
        run: docker build . --file /Dockerfile --tag my-image-name:$(date +%s)

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6